server {
    listen 80;
    server_name hub.deeke.cn;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name hub.deeke.cn;

    ssl_certificate     /etc/nginx/cert/hub.deeke.cn.pem;
    ssl_certificate_key /etc/nginx/cert/hub.deeke.cn.key;

    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types
        text/plain
        application/javascript
        application/x-javascript
        text/css
        application/xml
        text/javascript
        application/json
        image/jpeg
        image/gif
        image/png;
    gzip_vary on;

    # ======================
    # 前端 Vue/React SPA
    # ======================
    root /usr/share/nginx/html/deekeHub/antd/app/dist;
    index index.html;

    # 在 hub.deeke.cn 的 nginx 配置中加上
    location /livekit/ {
        proxy_pass http://106.13.xxx.xxx:7880/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ======================
    # API -> PHP
    # ======================
    location /api/ {
        root /var/www/html/deekeHub/php/public;

        # 去掉 /api 前缀
        rewrite ^/api/(.*)$ /$1 break;

        include fastcgi_params;
        fastcgi_pass php:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/html/deekeHub/php/public/index.php;
        fastcgi_param SCRIPT_NAME index.php;
    }

    # ======================
    # PHP（如果你有直接访问 php 文件的需求）
    # ======================
    location ~ \.php$ {
        root /var/www/html/deekeHub/php/public;
        include fastcgi_params;
        fastcgi_pass php:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
