[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=docker exec php php ./deekeHub/php/artisan queue:work redis --sleep=3 --tries=3 --queue=default
autostart=true
autorestart=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/home/deekeHubLog/laravel-worker.log
