[program:laravel-console]
process_name=%(program_name)s_%(process_num)02d
command=docker exec php php /var/www/html/deekeHub/php/artisan websocket:start
autostart=true
autorestart=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/home/deekeHubLog/laravel-console.log